version: '2'

services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: pitches
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass

  fastapi:
    build: .
    command: uvicorn pitch_health.main:app --host 0.0.0.0 --port 8000
    environment:
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      MONGO_USER: user
      MONGO_PASS: pass
    env_file:
      - .env
    ports:
      - 8000:8000

  test:
    build: .
    command: python -m unittest
