version: '2'

services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: pitches
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass

  fastapi:
    build: .
    environment:
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      MONGO_USER: user
      MONGO_PASS: pass
    ports:
      - 8000:8000
